### ISSUE TITLE
TODO/FIXME Count 15

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/rdf-canonize#28]
- [ ] TODO: convert algorithms to Promise-based async
       Commit: (7a6e52d) Browser bundle and Node.js 6 support.
       File:  [lib/index.js:104](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/index.js#L104)
       David I. Lehn commented 3 years ago

  - [ ] TODO: represent as byte buffer instead to cut memory usage in half
       Commit: (975909f) Add TODOs.
       File:  [lib/URDNA2015Sync.js:282](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015Sync.js#L282)
       Dave Longley commented 3 years ago

  - [ ] TODO: represent as byte buffer instead to cut memory usage in half
       Commit: (975909f) Add TODOs.
       File:  [lib/URDNA2015Sync.js:244](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015Sync.js#L244)
       Dave Longley commented 3 years ago

  - [ ] TODO: use `String.localeCompare`?
       Commit: (209593f) Convert synchronous algorithms to ES6.
       File:  [lib/URDNA2015Sync.js:152](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015Sync.js#L152)
       Dave Longley commented 3 years ago

  - [ ] TODO: consider changing `getId` to `issue`
       Commit: (209593f) Convert synchronous algorithms to ES6.
       File:  [lib/URDNA2015Sync.js:101](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015Sync.js#L101)
       Dave Longley commented 3 years ago

  - [ ] FIXME: may cause inaccurate total depth calculation
       Commit: (a09e3c4) Convert async algorithms to ES6.
       File:  [lib/URDNA2015.js:453](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L453)
       Dave Longley commented 3 years ago

  - [ ] FIXME: may cause inaccurate total depth calculation
       Commit: (a09e3c4) Convert async algorithms to ES6.
       File:  [lib/URDNA2015.js:418](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L418)
       Dave Longley commented 3 years ago

  - [ ] TODO: represent as byte buffer instead to cut memory usage in half
       Commit: (975909f) Add TODOs.
       File:  [lib/URDNA2015.js:337](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L337)
       Dave Longley commented 3 years ago

  - [ ] TODO: represent as byte buffer instead to cut memory usage in half
       Commit: (975909f) Add TODOs.
       File:  [lib/URDNA2015.js:283](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L283)
       Dave Longley commented 3 years ago

  - [ ] TODO: use `String.localeCompare`?
       Commit: (a09e3c4) Convert async algorithms to ES6.
       File:  [lib/URDNA2015.js:180](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L180)
       Dave Longley commented 3 years ago

  - [ ] TODO: consider changing `getId` to `issue`
       Commit: (a09e3c4) Convert async algorithms to ES6.
       File:  [lib/URDNA2015.js:118](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L118)
       Dave Longley commented 3 years ago

  - [ ] TODO: convert to ES6 iterable
       Commit: (b1fdcfd) Convert Permutator to ES6 class.
       File:  [lib/Permutator.js:6](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/Permutator.js#L6)
       Dave Longley commented 3 years ago

  - [ ] FIXME: support larger values
       Commit: (b9175e9) N-Quad serialization and optimization updates.
       File:  [lib/NQuads.js:375](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/NQuads.js#L375)
       David I. Lehn commented a year ago

  - [ ] TODO:
       Commit: (90455df) Improve acceptable N-Quads blank node labels.
       File:  [lib/NQuads.js:29](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/NQuads.js#L29)
       David I. Lehn commented 2 years ago

  - [ ] TODO: should also include an estimate of expectedWorkTime
       Commit: (a09e3c4) Convert async algorithms to ES6.
       File:  [lib/AsyncAlgorithm.js:47](https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/AsyncAlgorithm.js#L47)
       Dave Longley commented 3 years ago

**Comment by dlongley** [comment]
All TODOs / FIXMEs removed or are now old / covered by other issues.
